"""Generate the additive, closed facet HTTP family and provisioning-v2 artifacts."""

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACTS = ROOT / "contracts"
SCHEMAS = CONTRACTS / "schemas"
BASE = "https://cortext.local/spine/contracts/schemas/"
API = "spine.trusted-web-facets.v1"
GENERATED = {}


def save(path, value):
    GENERATED[path] = (json.dumps(value, indent=2) + "\n").encode()


def schema(name, **values):
    return {"$schema": "https://json-schema.org/draft/2020-12/schema", "$id": BASE + name, **values}


def closed(properties, required=None):
    return {
        "type": "object",
        "properties": properties,
        "required": list(properties) if required is None else required,
        "additionalProperties": False,
    }


def main():
    from spine.commands.registry import COMMAND_RUNTIME_CONTRACT_REGISTRY

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify generated bytes without writing")
    args = parser.parse_args()
    source = json.loads((CONTRACTS / "archetype-facet-contract-registry.v1.json").read_text())
    integration = json.loads((CONTRACTS / "archetype-facet-integration.v1.json").read_text())
    requests, responses, entries = {}, {}, []
    identity = {"$ref": "trusted-web-types.schema.json#/$defs/id"}
    decimal = {"$ref": "trusted-web-types.schema.json#/$defs/decimal"}
    for command, definition in sorted(source["commands"].items()):
        write = definition["mutates"]
        request = {"request": {"$ref": f"archetype-facet-commands.schema.json#/$defs/{command}"}}
        if write:
            request["expected_access_epoch"] = decimal
        requests[command] = closed(request)
        responses[command] = closed(
            {
                "contract_version": {"const": API},
                "ok": {"const": True},
                "identity_basis": {"const": "self_selected"},
                "account_id": identity,
                "subject_id": identity,
                "selection_id": identity,
                "access_epoch": decimal,
                "result_contract": {"const": definition["contract_version"]},
                "result": {"$ref": f"archetype-facet-responses.schema.json#/$defs/{command}"},
            }
        )
        entries.append(
            {
                "command": command,
                "path": f"/api/v1/facets/commands/{command}",
                "method": "POST",
                "access_mode": "write" if write else "read",
                "result_contract": definition["contract_version"],
                "required_contract_versions": list(COMMAND_RUNTIME_CONTRACT_REGISTRY[command].required_contract_versions),
                "resolvers": integration["permission_resolvers"][command],
                "replay_resolvers": integration["replay_permission_resolvers"].get(command, []),
            }
        )
    save(SCHEMAS / "trusted-web-facet-request.schema.json", schema("trusted-web-facet-request.schema.json", **{"$defs": requests}))
    save(SCHEMAS / "trusted-web-facet-response.schema.json", schema("trusted-web-facet-response.schema.json", **{"$defs": responses}))
    error_codes = [
        "invalid_request",
        "identity_unavailable",
        "operation_unavailable",
        "resource_unavailable",
        "access_changed",
        "command_id_unavailable",
        "domain_conflict",
        "domain_failure",
        "capacity_exceeded",
        "admission_unavailable",
    ]
    save(
        SCHEMAS / "trusted-web-facet-error.schema.json",
        schema(
            "trusted-web-facet-error.schema.json",
            **closed(
                {
                    "contract_version": {"const": API},
                    "ok": {"const": False},
                    "error": closed({"code": {"enum": error_codes}, "message": {"const": "Facet operation unavailable."}}),
                    "correlation_id": identity,
                    "selection_id": {"anyOf": [identity, {"type": "null"}]},
                }
            ),
        ),
    )
    registry = {
        "contract_version": "spine.trusted-web-facet-registry.v1",
        "api_contract": API,
        "discovery": {"method": "GET", "path": "/api/v1/facets/capabilities"},
        "commands": entries,
    }
    save(CONTRACTS / "spine.trusted-web-facet-registry.v1.json", registry)
    save(SCHEMAS / "trusted-web-facet-registry.schema.json", schema("trusted-web-facet-registry.schema.json", const=registry))
    save(
        SCHEMAS / "trusted-web-facet-capabilities.schema.json",
        schema(
            "trusted-web-facet-capabilities.schema.json",
            **closed(
                {
                    "contract_version": {"const": API},
                    "registry": {"$ref": "trusted-web-facet-registry.schema.json"},
                    "pagination_configured": {"type": "boolean"},
                }
            ),
        ),
    )
    # v1 remains byte-for-byte frozen. v2 adds only the facet_schema grant resource.
    for old in sorted(SCHEMAS.glob("trusted-web-provisioning-*.schema.json")):
        if old.name.endswith(".v2.schema.json"):
            continue
        value = json.loads(old.read_text())

        def transform(v):
            if isinstance(v, str):
                v = v.replace("spine.trusted-web-provisioning.v1", "spine.trusted-web-provisioning.v2")
                for filename in (
                    p.name for p in SCHEMAS.glob("trusted-web-provisioning-*.schema.json") if not p.name.endswith(".v2.schema.json")
                ):
                    v = v.replace(filename, filename.replace(".schema.json", ".v2.schema.json"))
            elif isinstance(v, list):
                if v == ["item", "item_archetype", "notification_profile"] or v == ["item_archetype", "notification_profile"]:
                    v = [*v, "facet_schema"]
                v = [transform(x) for x in v]
            elif isinstance(v, dict):
                v = {k: transform(x) for k, x in v.items()}
            return v

        save(old.with_name(old.name.replace(".schema.json", ".v2.schema.json")), transform(value))
    files = ["spine.trusted-web-facet-registry.v1.json", "archetype-facet-integration.v1.json"]
    files += ["schemas/" + p.name for p in SCHEMAS.glob("*facet*.schema.json")]
    files += ["schemas/" + p.name for p in SCHEMAS.glob("trusted-web-provisioning-*.v2.schema.json")]
    files += ["schemas/trusted-web-types.schema.json"]
    files += [str(p.relative_to(CONTRACTS)) for p in GENERATED]
    save(
        CONTRACTS / "trusted-web-facet-pins.v1.json",
        {
            "contract_version": "spine.trusted-web-facet-pins.v1",
            "files": {
                name: hashlib.sha256(GENERATED.get(CONTRACTS / name) or (CONTRACTS / name).read_bytes()).hexdigest()
                for name in sorted(set(files))
            },
        },
    )
    changed = [p for p, raw in GENERATED.items() if not p.exists() or p.read_bytes() != raw]
    if args.check:
        for path in changed:
            print(path.relative_to(ROOT))
        return int(bool(changed))
    for path, raw in GENERATED.items():
        path.write_bytes(raw)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
